### ISSUE TITLE
Interval Trigger not Triggering Scripts

### ISSUE THREAD

**Issue by LDShadowLord** [simse/chronos#17]
Running Unraid 6.8.3

I have several scripts running that do various things, but I notice that after the weekly restart (To back the docker containers up) the scripts run for a couple of days, and then fail to run.
Restarting the docker container fixes the issue temporarily.

Manually executing the script, changing the timer or turning the timer off and on again do not fix the issue.

There are no logs or errors being reported, and the container is staying running.

**Comment by simse** [comment]
When you say restarting fixes the issue temporarily, do you mean it's fixed until next time the plugin restarts the containers?

**Comment by LDShadowLord** [comment]
> do you mean it's fixed until next time the plugin restarts the containers?

No, it's fixed for a day or two and then it stops working. My restart script restarts at 3am on a Monday, and according to the database the last time the script ran was 6pm that same monday. So 15 hours before it stops running again.
Restarting the chronos container will give me another day or so before failure.

**Comment by simse** [comment]
Strange, and what's the last thing the logs are saying?

**Comment by LDShadowLord** [comment]
This is the last log before the crash (Logs taken from Portainer)
`Tick: 52244


2020-03-23 18:00:10.876500Starting migrations
There is nothing to migrate`

The next log after that was when I restarted the container.

**Comment by LDShadowLord** [comment]
I also noticed it not running again a moment ago (Only 5 hours after restart) and when I checked the logs I found this:

> Exception in thread Thread-1:


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql


    cursor.execute(sql, params or ())


sqlite3.OperationalError: database is locked




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner


    self.run()


  File "/usr/local/lib/python3.7/threading.py", line 870, in run


    self._target(*self._args, **self._kwargs)


  File "chronos.py", line 25, in main


    tick(i)


  File "/app/chronos/chronos/runtime.py", line 77, in tick


    for script in chronos.metadata.Script.select():


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6655, in __iter__


    self.execute()


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1812, in inner


    return method(self, database, *args, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1883, in execute


    return self._execute(database)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2054, in _execute


    cursor = database.execute(self)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3018, in execute


    return self.execute_sql(sql, params, commit=commit)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3012, in execute_sql


    self.commit()


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2783, in __exit__


    reraise(new_type, new_type(*exc_args), traceback)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 183, in reraise


    raise value.with_traceback(tb)


  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql


    cursor.execute(sql, params or ())


peewee.OperationalError: database is locked

**Comment by simse** [comment]
This issue should now be fixed.
